name: Checks
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.22'
          python-version: '3.11'
      - run: uv sync --locked --dev
      - run: uv run ruff check .
      - run: uv run pytest
